{% set version = "2.7.0" %}

package:
  name: openldap
  version: {{ version }}

source:
  url: https://openldap.org/software/download/OpenLDAP/openldap-release/openldap-{{ version }}.tgz
  sha256: 9e86f37da375aa948a1b478dd76fe87b02090e47c21facae19223588e3407922

build:
  number: 0
  run_exports:
    - {{ pin_subpackage('openldap', max_pin='x.x') }}

requirements:
  build:
    - gnuconfig  # [unix]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}  # [unix]
    - make  # [unix]
    - groff  # [unix]
  host:
    - openssl
    - cyrus-sasl
    - krb5  # [unix]
  run:
    - openssl
    - cyrus-sasl

test:
  commands:
    - test $PREFIX/include/ldap.h   # [unix]
    - if not exist %LIBRARY_INC%\ldap.h exit 1  # [win]
    - if not exist %LIBRARY_BIN%\libldap.dll exit 1  # [win]
    - if not exist %LIBRARY_BIN%\liblber.dll exit 1  # [win]
    - if not exist %LIBRARY_LIB%\libldap.lib exit 1  # [win]
    - if not exist %LIBRARY_LIB%\liblber.lib exit 1  # [win]

about:
  home: https://www.openldap.org
  license: OLDAP-2.8
  license_family: BSD
  license_file: LICENSE
  summary: >
    OpenLDAP Software is an open source implementation of the Lightweight Directory Access Protocol.
  doc_url: https://www.openldap.org/doc/
  dev_url: https://www.openldap.org/software/repo.html

extra:
  recipe-maintainers:
    - mariusvniekerk
    - bollwyvl
