{% set version = "2.6.5" %}

package:
  name: openldap
  version: {{ version }}

source:
  url: https://openldap.org/software/download/OpenLDAP/openldap-release/openldap-{{ version }}.tgz
  sha256: 2e27a8d4f4c2af8fe840b573271c20aa163e24987f9765214644290f5beb38d9

build:
  number: 1
  skip: true  # [not unix]
  run_exports:
    - {{ pin_subpackage('openldap', max_pin='x.x') }}

requirements:
  build:
    - gnuconfig  # [unix]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - make
    - groff
  host:
    - openssl
    - cyrus-sasl
    - krb5
  run:
    - openssl
    - cyrus-sasl

test:
  commands:
    - test $PREFIX/include/ldap.h   # [unix]

about:
  home: https://www.openldap.org
  license: OLDAP-2.8
  license_family: BSD
  license_file: LICENSE
  summary: >
    OpenLDAP Software is an open source implementation of the Lightweight Directory Access Protocol.
  doc_url: https://www.openldap.org/doc/
  dev_url: https://www.openldap.org/software/repo.html

extra:
  recipe-maintainers:
    - mariusvniekerk
    - bollwyvl
